In [108]:
import json
import pickle
import numpy
import pandas
from pandas import DataFrame
pandas.set_option('display.max_rows', 100)

In [109]:
epLat = 0.012160099999998054
epLng = 0.014610749999992125
epTime = 255

In [110]:
with open('trajTrain.pickle','rb') as f:
    trajTrainDict = pickle.load(f)
    trajTrain = trajTrainDict['trajTrain']
    trajTrainOri = trajTrainDict['trajTrainOri']
    mappingTrain = trajTrainDict['mappingTrain']

In [111]:
with open('trajTest.pickle','rb') as f:
    trajTrainDict = pickle.load(f)
    trajTest = trajTrainDict['trajTest']
    trajTestOri = trajTrainDict['trajTestOri']
    mappingTest = trajTrainDict['mappingTest']

In [264]:
def getOverlayOneCubeWithPointAmount(trajList1,trajList2,dtime,distX,distY,angDiffConst,pointAmountRatio = 0):
    maxTime = trajList1[9] + dtime
    minTime = trajList1[9] - dtime
    trajList3 = trajList2.loc[(trajList2[9] > minTime) & (trajList2[9] < maxTime),]
    trajList4 = trajList3.loc[abs(trajList3[9] - trajList1[9]) < dtime,]
    trajList4 = trajList4.loc[abs(trajList4[3] - trajList1[3]) < distX,]
    trajList4 = trajList4.loc[abs(trajList4[4] - trajList1[4]) < distY,]
    trajList4 = trajList4.loc[angleDiff(trajList4[8],trajList1[8]) < angDiffConst,]
    while pointAmountRatio > 0:
        trajList5 = trajList4.loc[abs(trajList4[0] - trajList1[0]) < (trajList1[0] * (1-pointAmountRatio) ),]
        if trajList5.size > 0:
            trajList4 = trajList5
            break
        pointAmountRatio -= 0.1
    if trajList4.size <= 0:
        return None
    n1 = trajList4.shape[0]
    area1 = DataFrame(numpy.zeros((n1,3), dtype=int))
    area1[0] = trajList4[5].values  #其它軌
    area1[1] = trajList4[1].values  #其它軌第幾cube
    area1[2] = trajList4.index.values  #其它軌此cube在總名單上第幾
    return area1

In [113]:
def getOverlayOneCube(trajList1,trajList2,dtime,distX,distY,angDiffConst):
	maxTime = trajList1[9] + dtime
	minTime = trajList1[9] - dtime
	trajList3 = trajList2.loc[(trajList2[9] > minTime) & (trajList2[9] < maxTime),]
	trajList4 = trajList3.loc[abs(trajList3[9] - trajList1[9]) < dtime,]
	trajList4 = trajList4.loc[abs(trajList4[3] - trajList1[3]) < distX,]
	trajList4 = trajList4.loc[abs(trajList4[4] - trajList1[4]) < distY,]
	trajList4 = trajList4.loc[angleDiff(trajList4[8],trajList1[8]) < angDiffConst,]
	n1 = trajList4.shape[0]
	area1 = DataFrame(numpy.zeros((n1,3), dtype=int))
	area1[0] = trajList4[5].values  #其它軌
	area1[1] = trajList4[1].values  #其它軌第幾cube
	area1[2] = trajList4.index.values  #其它軌此cube在總名單上第幾
	return area1

In [114]:
def angleDiff(a ,b):
	result = abs(a - b)
	result = result.values
	if len(a) > 1:
		index = result > 180
		result[index] = 360 - result[index]
	else:
		if result > 180:
			result = 360 - result
	return result

In [115]:
def getMaxGroup(trajList):
	aList = trajList[10] - trajList[9]
	arr = numpy.array(aList)
	result = numpy.zeros(arr.size)
	n = arr.size
	ratio = n // 2
	for i in range(n):
		x1 = abs(arr - arr[i])
		x2 = numpy.sort(x1)
		result[i] = sum(x2[:ratio])
	minLoc = numpy.where(result == numpy.amin(result))
	if minLoc[0][0] >= 0:
		return arr[minLoc[0][0]]
	else:
		raise Exception('ERROR: getMaxGroup: minLoc[0][0] = %i < 0' % minLoc[0][0])

In [116]:
def ignoreBeginOrLastOnePointCube(traj,trajOri,mapping):
    hist = numpy.bincount(mapping[4])
    hist2 = numpy.bincount(hist)
    ratioOfMostGap = 0.2
    lessGap = numpy.where((hist2.cumsum() / hist2.sum()) <= ratioOfMostGap)[0][-1] 
    #get lessGap
    n = hist.__len__()
    indexTop = 0
    indexTop2 = 0
    for i in range(n):
        if hist[i] <= lessGap :
            indexTop += 1
            indexTop2 += 1
        else:
            break
    indexEnd = traj.shape[0] - 1
    indexEnd2 = trajOri.shape[0] - 1
    for i in range(n-1,0,-1):
        if hist[i] <= lessGap :
            indexEnd -= 1
            indexEnd2 -= 1
        else:
            break
    return (traj.iloc[indexTop:(indexEnd+1),:].copy(),trajOri.iloc[indexTop2:(indexEnd2+1),:].copy())

In [156]:
from math import cos
from math import sin
from math import radians
from math import asin
import numpy

def getDistance(x,y):
	Long1,Lat1 = x
	Long2,Lat2 = y
	deltaX = cos(radians(Lat2))*cos(radians(Long2)) \
			 - cos(radians(Lat1)) * cos(radians(Long1))
	deltaY = cos(radians(Lat2))*sin(radians(Long2)) \
			 - cos(radians(Lat1)) * sin(radians(Long1))
	deltaZ = sin(radians(Lat2)) - sin(radians(Lat1))
	C = numpy.linalg.norm(numpy.array([deltaX, deltaY, deltaZ]))
	deltaSigma = 2 * asin(C/2)
	d = round( 6371 * 1000 * deltaSigma )
	return d

In [217]:
import math

def getFullTime(commonTime, cube1,cube2):
    dist = getDistance((cube1[11],cube1[13]),
                (cube1[12],cube1[14]))
    dist2 = getDistance((cube1[11],cube1[13]),
                (cube2[11],cube2[13]))   
    return math.ceil(commonTime / dist * dist2)

In [334]:
#單獨測一個test traj
targetTrajNo = 60
targetTraj = trajTest.loc[trajTest[5] == targetTrajNo,].copy()
targetTrajOri = trajTestOri.loc[trajTestOri[5] == targetTrajNo,].copy()
targetMapping = mappingTest.loc[mappingTest[2] == targetTrajNo,].copy()
targetNew,targetOriNew = ignoreBeginOrLastOnePointCube(targetTraj,targetTrajOri,targetMapping)
realTime = targetNew.iloc[-1,10]-targetNew.iloc[0,9]
totalTime = 0
n = targetNew.shape[0]
commonTime = 0
#for i2 in range(n):

In [335]:
#單獨測一個test traj , continue
#i2 = 6
tempExpResult = numpy.zeros((n,2),dtype='int')
tempExpResult[:,0] = targetNew.iloc[:,10] - targetNew.iloc[:,9]
listArea = []
for i2 in range(n):
    if i2 > 0:
            #print(targetTraj.iloc[i2,9],',',targetTraj.iloc[i2-1, 9] + commonTime)
            targetNew.iloc[i2,9] = targetNew.iloc[i2-1, 9] + commonTime
    #area = getOverlayOneCubeWithPointAmount(targetNew.iloc[i2,],3600,epLng,epLat,50)
    #if area is None:
    area = getOverlayOneCube(targetNew.iloc[i2,],
                                 trajTrain,
                                 3600,
                                 epLng,
                                 epLat,
                                 50)
    #        print('None apear, i2=',i2)
    listArea.append(area)
    commonTime = getMaxGroup(trajTrain.loc[area[2],])
    if i2 < (n-1):
        commonTime = getFullTime(commonTime, targetNew.iloc[i2,], targetNew.iloc[i2+1,])
    tempExpResult[i2,1] = commonTime
    totalTime += commonTime

In [336]:
tempExpResult

array([[101,  79],
       [101,  79],
       [ 71,  72],
       [ 69,  83],
       [ 71,  82],
       [ 99,  93],
       [190, 335],
       [ 91,  84],
       [214, 265],
       [247,  86],
       [239,  92]])

In [68]:
print(realTime)
print(totalTime)

2569
2414

In [41]:
targetNew

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
428,8,0,2690,104.036754,30.594354,60,1331,1062,39,2640,2741,104.029804,104.043704,30.589579,30.599128
429,6,1,2820,104.053461,30.598173,60,1288,-23,-1,2770,2871,104.046730,104.060192,30.598346,30.598141
430,8,2,2916,104.068971,30.598010,60,1314,-18,-1,2881,2952,104.062107,104.075835,30.598093,30.597927
431,8,3,2996,104.084198,30.596784,60,1213,-249,-12,2962,3031,104.077861,104.090535,30.597902,30.595665
432,8,4,3076,104.099844,30.595070,60,1365,45,2,3041,3112,104.092712,104.106975,30.595180,30.595586
433,6,5,3171,104.115413,30.596476,60,1227,151,7,3122,3221,104.109003,104.121823,30.595797,30.597154
434,5,6,3959,104.123902,30.600524,60,-183,615,107,3864,4054,104.123523,104.121610,30.597760,30.603287
435,7,7,4198,104.112965,30.605328,60,-1229,-46,-178,4153,4244,104.119383,104.106546,30.605266,30.604852
436,4,8,4362,104.103144,30.605762,60,-46,201,103,4255,4469,104.104235,104.103751,30.604860,30.606664
437,6,9,4834,104.098311,30.606151,60,-916,-81,-175,4711,4958,104.103096,104.093527,30.606759,30.606032
438,10,10,5089,104.084401,30.611493,60,-1363,1178,139,4970,5209,104.091521,104.077282,30.606195,30.616790

In [42]:
targetTraj

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
428,8,0,2690,104.036754,30.594354,60,1331,1062,39,2640,2741,104.029804,104.043704,30.589579,30.599128
429,6,1,2820,104.053461,30.598173,60,1288,-23,-1,2770,2871,104.046730,104.060192,30.598346,30.598141
430,8,2,2916,104.068971,30.598010,60,1314,-18,-1,2881,2952,104.062107,104.075835,30.598093,30.597927
431,8,3,2996,104.084198,30.596784,60,1213,-249,-12,2962,3031,104.077861,104.090535,30.597902,30.595665
432,8,4,3076,104.099844,30.595070,60,1365,45,2,3041,3112,104.092712,104.106975,30.595180,30.595586
433,6,5,3171,104.115413,30.596476,60,1227,151,7,3122,3221,104.109003,104.121823,30.595797,30.597154
434,5,6,3959,104.123902,30.600524,60,-183,615,107,3864,4054,104.123523,104.121610,30.597760,30.603287
435,7,7,4198,104.112965,30.605328,60,-1229,-46,-178,4153,4244,104.119383,104.106546,30.605266,30.604852
436,4,8,4362,104.103144,30.605762,60,-46,201,103,4255,4469,104.104235,104.103751,30.604860,30.606664
437,6,9,4834,104.098311,30.606151,60,-916,-81,-175,4711,4958,104.103096,104.093527,30.606759,30.606032
438,10,10,5089,104.084401,30.611493,60,-1363,1178,139,4970,5209,104.091521,104.077282,30.606195,30.616790
439,2,11,5259,104.077178,30.618739,60,12,71,80,5239,5280,104.077115,104.077241,30.618418,30.619060

In [39]:
trajTest.loc[trajTest[5] == 60,]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
428,8,0,2690,104.036754,30.594354,60,1331,1062,39,2640,2741,104.029804,104.043704,30.589579,30.599128
429,6,1,2820,104.053461,30.598173,60,1288,-23,-1,2770,2871,104.046730,104.060192,30.598346,30.598141
430,8,2,2916,104.068971,30.598010,60,1314,-18,-1,2881,2952,104.062107,104.075835,30.598093,30.597927
431,8,3,2996,104.084198,30.596784,60,1213,-249,-12,2962,3031,104.077861,104.090535,30.597902,30.595665
432,8,4,3076,104.099844,30.595070,60,1365,45,2,3041,3112,104.092712,104.106975,30.595180,30.595586
433,6,5,3171,104.115413,30.596476,60,1227,151,7,3122,3221,104.109003,104.121823,30.595797,30.597154
434,5,6,3959,104.123902,30.600524,60,-183,615,107,3864,4054,104.123523,104.121610,30.597760,30.603287
435,7,7,4198,104.112965,30.605328,60,-1229,-46,-178,4153,4244,104.119383,104.106546,30.605266,30.604852
436,4,8,4362,104.103144,30.605762,60,-46,201,103,4255,4469,104.104235,104.103751,30.604860,30.606664
437,6,9,4834,104.098311,30.606151,60,-916,-81,-175,4711,4958,104.103096,104.093527,30.606759,30.606032
438,10,10,5089,104.084401,30.611493,60,-1363,1178,139,4970,5209,104.091521,104.077282,30.606195,30.616790
439,2,11,5259,104.077178,30.618739,60,12,71,80,5239,5280,104.077115,104.077241,30.618418,30.619060

In [302]:
trajNoList = numpy.unique(trajTest[5])

expResult = numpy.zeros((trajNoList.size+1,5),dtype='int')
expResult[:,2] = 1
expResult[:,4] = list(range(trajNoList.size+1))

#expTotalResult = 0
for targetTrajNo in trajNoList[0:100]:
    #targetTrajNo = 2
    print('targetTrajNo=',targetTrajNo)
    totalTime,realTime,realTime2,tempExpResult = \
        getTestResult4OneTarget(targetTrajNo,
                            trajTest,
                            trajTestOri,
                            mappingTest,
                            trajTrain,
                            trajTrainOri,
                            mappingTrain,
                            epLng,epLat)
    expResult[targetTrajNo,0] = realTime2
    expResult[targetTrajNo,1] = totalTime
    expResult[targetTrajNo,2] = 0
    expResult[targetTrajNo,3] = realTime
#expTotalResult += abs(totalTime-realTime) / realTime
#print(trajNoList.size)

targetTrajNo= 1
0
1
2
3
4
targetTrajNo= 2
0
1
2
3
4
5
6
7
8
9
targetTrajNo= 3
0
1
2
3
4
5
targetTrajNo= 4
0
1
2
3
4
5
6
7
targetTrajNo= 5
0
1
2
3
4
5
6
7
8
targetTrajNo= 6
0
1
2
3
4
5
6
7
targetTrajNo= 7
0
1
2
targetTrajNo= 8
0
1
2
3
4
5
6
7
targetTrajNo= 9
0
1
2
3
4
5
6
7
8
targetTrajNo= 10
0
1
2
3
targetTrajNo= 11
0
1
2
3
4
5
6
7
targetTrajNo= 12
0
1
2
3
4
5
6
7
targetTrajNo= 13
0
1
2
3
targetTrajNo= 14
0
1
2
3
4
targetTrajNo= 15
0
1
2
3
4
5
targetTrajNo= 16
0
1
2
3
4
5
6
7
8
targetTrajNo= 17
0
1
2
3
4
5
targetTrajNo= 18
0
1
2
3
4
5
targetTrajNo= 19
0
1
2
3
4
targetTrajNo= 20
0
1
2
3
4
5
6
targetTrajNo= 21
0
1
2
3
4
5
6
targetTrajNo= 22
0
1
2
3
4
5
targetTrajNo= 23
0
1
2
3
4
5
6
7
targetTrajNo= 24
0
1
2
3
4
5
targetTrajNo= 25
0
1
2
3
4
targetTrajNo= 26
0
1
2
3
4
targetTrajNo= 27
0
1
2
3
4
5
6
7
8
9
10
11
targetTrajNo= 28
0
1
2
3
4
5
6
7
8
9
10
11
targetTrajNo= 29
0
1
2
3
4
5
targetTrajNo= 30
0
1
2
3
targetTrajNo= 31
0
1
2
3
4
5
6
7
targetTrajNo= 32
0
1
2
3
4
5
6
targetTrajNo= 33
0
1
2
3
4
targetTrajNo= 34
0
1
2
3
4
5
6
7
targetTrajNo= 35
0
1
2
3
4
5
targetTrajNo= 36
0
1
2
3
targetTrajNo= 37
0
1
2
3
4
5
6
targetTrajNo= 38
0
1
2
3
4
5
targetTrajNo= 39
0
1
2
3
4
5
6
targetTrajNo= 40
0
1
2
3
4
5
6
7
8
targetTrajNo= 41
0
1
2
3
4
targetTrajNo= 42
0
1
2
3
4
5
6
7
targetTrajNo= 43
0
1
2
3
4
targetTrajNo= 44
0
1
2
3
4
5
6
targetTrajNo= 45
0
1
2
3
4
targetTrajNo= 46
0
1
2
3
4
5
targetTrajNo= 47
0
1
2
3
4
targetTrajNo= 48
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
targetTrajNo= 49
0
1
2
3
4
5
6
targetTrajNo= 50
0
1
2
3
targetTrajNo= 51
0
1
2
3
4
5
targetTrajNo= 52
0
1
2
3
4
5
targetTrajNo= 53
0
1
2
3
4
5
6
7
8
9
targetTrajNo= 54
0
1
2
3
4
5
6
targetTrajNo= 55
0
1
2
3
4
targetTrajNo= 56
0
1
2
3
4
5
6
7
targetTrajNo= 57
0
1
2
3
4
5
6
7
8
targetTrajNo= 58
0
1
2
3
4
targetTrajNo= 59
0
1
2
3
targetTrajNo= 60
0
1
2
3
4
5
6
7
8
9
10
targetTrajNo= 61
0
1
2
3
targetTrajNo= 62
0
1
2
3
4
5
6
7
8
9
10
11
targetTrajNo= 63
0
1
2
3
targetTrajNo= 64
0
1
2
3
4
5
targetTrajNo= 65
0
1
2
3
4
targetTrajNo= 66
0
1
2
3
targetTrajNo= 67
0
1
2
3
targetTrajNo= 68
0
1
2
3
4
5
targetTrajNo= 69
0
1
2
3
targetTrajNo= 70
0
1
2
3
targetTrajNo= 71
0
1
2
targetTrajNo= 72
0
1
2
3
4
targetTrajNo= 73
0
1
2
3
targetTrajNo= 74
0
1
2
3
4
5
targetTrajNo= 75
0
1
2
3
4
5
targetTrajNo= 76
0
1
2
3
4
5
6
targetTrajNo= 77
0
1
2
3
4
5
targetTrajNo= 78
0
1
2
3
4
5
6
7
targetTrajNo= 79
0
1
2
3
targetTrajNo= 80
0
1
2
3
targetTrajNo= 81
0
1
2
3
4
5
6
7
8
9
targetTrajNo= 82
0
1
2
3
4
5
targetTrajNo= 83
0
1
2
3
targetTrajNo= 84
0
1
2
3
4
targetTrajNo= 85
0
1
2
3
4
targetTrajNo= 86
0
1
2
3
targetTrajNo= 87
0
1
2
3
targetTrajNo= 88
0
1
2
3
targetTrajNo= 89
0
1
2
3
4
targetTrajNo= 90
0
1
2
3
4
5
6
targetTrajNo= 91
0
1
2
3
4
5
6
7
targetTrajNo= 92
0
1
2
3
4
5
6
targetTrajNo= 93
0
1
2
3
targetTrajNo= 94
0
1
2
3
targetTrajNo= 95
0
1
2
3
targetTrajNo= 96
0
1
2
3
4
5
targetTrajNo= 97
0
1
2
3
4
5
6
7
targetTrajNo= 98
0
1
2
3
4
5
targetTrajNo= 99
0
1
2
targetTrajNo= 100
0
1
2
3
4
5
6

In [306]:
expResult[:,4] = list(range(trajNoList.size+1))
expResult[1:101]

array([[ 816,  959,    0,  816,    1],
       [1894, 1902,    0, 2494,    2],
       [1095, 1206,    0, 1095,    3],
       [1583, 1704,    0, 1583,    4],
       [1994, 1782,    0, 1994,    5],
       [1554, 1633,    0, 2034,    6],
       [ 493,  922,    0,  493,    7],
       [1033,  976,    0, 1033,    8],
       [1091, 1128,    0, 1091,    9],
       [ 722,  655,    0,  722,   10],
       [1972, 2115,    0, 1972,   11],
       [ 779, 1429,    0,  779,   12],
       [ 897,  697,    0, 2270,   13],
       [2152, 1386,    0, 2152,   14],
       [1546, 1403,    0, 1546,   15],
       [2363, 2448,    0, 2363,   16],
       [1389, 1387,    0, 1389,   17],
       [1590, 1583,    0, 1590,   18],
       [1316, 1291,    0, 1316,   19],
       [1942, 1580,    0, 1942,   20],
       [1802, 1697,    0, 1802,   21],
       [1425, 1489,    0, 1425,   22],
       [1860, 2022,    0, 1860,   23],
       [1368, 1314,    0, 1368,   24],
       [1218, 1246,    0, 1218,   25],
       [1263, 1216,    0, 1263,   26],
       [3193, 2843,    0, 3193,   27],
       [3203, 2048,    0, 3203,   28],
       [1730, 1176,    0, 1730,   29],
       [1118,  739,    0, 1118,   30],
       [2157, 1534,    0, 2157,   31],
       [1959, 1599,    0, 1959,   32],
       [1283, 1292,    0, 1283,   33],
       [1410, 1236,    0, 1510,   34],
       [1670, 1572,    0, 1670,   35],
       [ 635,  571,    0,  635,   36],
       [ 922, 1109,    0,  922,   37],
       [1056,  865,    0, 1056,   38],
       [1204, 1057,    0, 1449,   39],
       [1262, 1177,    0, 1501,   40],
       [ 673,  639,    0,  673,   41],
       [1159, 1309,    0, 1430,   42],
       [1072,  802,    0, 1072,   43],
       [1973, 1248,    0, 1973,   44],
       [1463,  979,    0, 1463,   45],
       [1562, 1207,    0, 1562,   46],
       [ 531,  566,    0,  531,   47],
       [3137, 2291,    0, 3137,   48],
       [ 956, 1082,    0, 1147,   49],
       [ 661, 2692,    0,  661,   50],
       [1334, 1829,    0, 1334,   51],
       [1143,  991,    0, 1143,   52],
       [2247, 1795,    0, 2247,   53],
       [1545, 1185,    0, 1545,   54],
       [1072, 1082,    0, 1072,   55],
       [1416, 1634,    0, 1416,   56],
       [2439, 1368,    0, 2439,   57],
       [ 489,  537,    0,  489,   58],
       [1216,  760,    0, 1216,   59],
       [1684, 1736,    0, 2569,   60],
       [ 964, 1805,    0,  964,   61],
       [3271, 2832,    0, 3271,   62],
       [ 907,  818,    0,  907,   63],
       [1559, 1284,    0, 2172,   64],
       [1115, 1288,    0, 1115,   65],
       [ 935,  763,    0,  935,   66],
       [ 834,  844,    0,  834,   67],
       [1458, 1246,    0, 1668,   68],
       [ 986,  879,    0,  986,   69],
       [ 906,  798,    0,  906,   70],
       [ 888,  654,    0,  888,   71],
       [1136,  882,    0, 1336,   72],
       [ 967,  929,    0,  967,   73],
       [1573, 1604,    0, 1573,   74],
       [1557, 1302,    0, 1557,   75],
       [1730, 1287,    0, 1730,   76],
       [1540, 1130,    0, 1540,   77],
       [2709, 2291,    0, 2709,   78],
       [1056, 1009,    0, 1056,   79],
       [ 865,  872,    0,  865,   80],
       [3087, 2052,    0, 3087,   81],
       [1561, 1102,    0, 1561,   82],
       [ 882, 1001,    0,  882,   83],
       [1021, 1039,    0, 1609,   84],
       [1251, 1153,    0, 1251,   85],
       [ 959, 1104,    0,  959,   86],
       [ 789,  741,    0,  789,   87],
       [ 922,  961,    0,  922,   88],
       [1257, 1150,    0, 1257,   89],
       [1780, 1979,    0, 2670,   90],
       [1819, 1853,    0, 1819,   91],
       [1975, 1558,    0, 1975,   92],
       [ 722,  597,    0,  722,   93],
       [1013, 1003,    0, 1013,   94],
       [ 983, 1019,    0,  983,   95],
       [1488, 1678,    0, 1488,   96],
       [1831, 1655,    0, 1831,   97],
       [1160, 1277,    0, 1160,   98],
       [ 628,  765,    0,  628,   99],
       [1399, 1472,    0, 1399,  100]])

In [265]:
from dtw import accelerated_dtw

def getDTWeachRow(row,x,mappingTrain,trajTrainOri):
    tempTrajOriNo = mappingTrain.loc[ 
            (mappingTrain[2] == row[5]) & 
            (mappingTrain[4] == row[1])
            ,3].to_list()
    y = trajTrainOri.loc[ 
            (trajTrainOri[5] == row[5]) & 
            (trajTrainOri[1].isin( tempTrajOriNo ))
            ,[3,4]].to_numpy()
    d, cost_matrix, acc_cost_matrix, path = accelerated_dtw(x,y,getDistance)
    return d

In [298]:
from dtw import accelerated_dtw

def getTimeByMinDtw(targetNo, 
                    area,
                    targetTrajOri,
                    targetMapping,
                    trajTrain,
                    trajTrainOri,
                    mappingTrain):
    trajTrainCubesIndex = area[2]
    
    targetTrajOriResetIndex = targetTrajOri.set_index(1)
    x = targetTrajOriResetIndex.loc[ 
            targetMapping.loc[ targetMapping[4] == targetNo ,3 ] ,
            [3,4]
        ].to_numpy()

    #result = []
    dfTrajNoWiCubeNo = trajTrain.loc[trajTrainCubesIndex,[5,1]]
    n = dfTrajNoWiCubeNo.shape[0]
    result = dfTrajNoWiCubeNo.apply(getDTWeachRow,axis=1,args=(x,mappingTrain,trajTrainOri))
    minIndex = result.idxmin()   
    minTrajTrain = trajTrain.loc[minIndex,]
    commonTime = trajTrain.loc[minIndex,10] - trajTrain.loc[minIndex,9]
    
    mappingTrain
    listTrajOri = mappingTrain.loc[ 
            (mappingTrain[2] == minTrajTrain[5]) & 
            (mappingTrain[4] == minTrajTrain[1])
            ,3].to_list()
    y = trajTrainOri.loc[ 
            (trajTrainOri[5] == minTrajTrain[5]) & 
            (trajTrainOri[1].isin( listTrajOri ))
            ,2].to_numpy()
    y[-1] - 
    
    return commonTime
    '''
    #minDtw = -1
    #minIndex = -1
    for i in range(n):
        tempTrajOriNo = mappingTrain.loc[ 
            (mappingTrain[2] == dfTrajNoWiCubeNo[5].iloc[i]) & 
            (mappingTrain[4] == dfTrajNoWiCubeNo[1].iloc[i])
            ,3].to_list()
        y = trajTrainOri.loc[ 
            (trajTrainOri[5] == dfTrajNoWiCubeNo[5].iloc[i]) & 
            (trajTrainOri[1].isin( tempTrajOriNo ))
            ,[3,4]].to_numpy()
        d, cost_matrix, acc_cost_matrix, path = accelerated_dtw(x,y,getDistance)
        if (minDtw <= -1) | (d < minDtw):
            minDtw = d
            minIndex = dfTrajNoWiCubeNo.index[i]
        #result.append(d)
    if minIndex <= -1:
        raise Exception('ERROR: getTimeByMinDtw(): minIndex is -1')
    '''

 here 改這裡
 為什麼targetTrajNo = 50算出來會多那麼多時間

In [325]:
#單獨測一個test traj
import math

targetTrajNo = 50

targetTraj = trajTest.loc[trajTest[5] == targetTrajNo,].copy()
targetTrajOri = trajTestOri.loc[trajTestOri[5] == targetTrajNo,].copy()
targetMapping = mappingTest.loc[mappingTest[2] == targetTrajNo,].copy()
targetNew,targetOriNew = ignoreBeginOrLastOnePointCube(targetTraj,targetTrajOri,targetMapping)
targetNew2 = targetNew.copy()
realTime = targetNew.iloc[-1,10]-targetNew.iloc[0,9]
realTime2 = realTime
totalTime = 0
n = targetNew.shape[0]
commonTime = 0

ratioOfMostGap = 0.9
timeDiff = targetTrajOri[2].iloc[1:].to_numpy() - targetTrajOri[2].iloc[:-1].to_numpy()
timeDiff = timeDiff.astype('int')
timeDiff = numpy.sort(timeDiff)
iarr = math.ceil(timeDiff.size * ratioOfMostGap)
timeDiffTop = timeDiff[iarr] * 2

#for i2 in range(n):

#單獨測一個test traj , continue
#i2 = 6
tempExpResult = numpy.zeros((n,3),dtype='int')
tempExpResult[:,0] = targetNew.iloc[:,10] - targetNew.iloc[:,9]
listArea = []
for i2 in range(n):
    print(i2)
    if i2 > 0:
            #print(targetTraj.iloc[i2,9],',',targetTraj.iloc[i2-1, 9] + commonTime)
            targetNew.iloc[i2,9] = targetNew.iloc[i2-1, 9] + commonTime
    #getOverlayOneCubeWithPointAmount內部改成None就重算
    area = getOverlayOneCubeWithPointAmount(targetNew.iloc[i2,],
                                 trajTrain,
                                 3600,
                                 epLng,
                                 epLat,
                                 10,0.7)
    if area is None:
        print('ERROR: index=',i2,' area is None')
        continue
    #listArea.append(area)
    #commonTime = getMaxGroup(trajTrain.loc[area[2],])
    commonTime = getTimeByMinDtw(targetNew.iloc[i2,1], 
                    area,
                    targetOriNew,
                    targetMapping,
                    trajTrain,
                    trajTrainOri,
                    mappingTrain)
    tempExpResult[i2,1] = commonTime
    
    if i2 < (n-1):
        cubeTimeDiff = targetNew2.iloc[i2+1,9] - targetNew2.iloc[i2,10]
        if cubeTimeDiff > timeDiffTop:
            realTime2 -= cubeTimeDiff
        else:
            commonTime = getFullTime(commonTime, targetNew.iloc[i2,], targetNew.iloc[i2+1,])
    tempExpResult[i2,2] = commonTime
    totalTime += commonTime
    if i2 == 1:
        break

0
1

In [331]:
#getDistance((targetNew.iloc[0,11],targetNew.iloc[0,13]),(targetNew.iloc[0,12],targetNew.iloc[0,14]))
getDistance((targetNew.iloc[0,11],targetNew.iloc[0,13]),(targetNew.iloc[1,11],targetNew.iloc[1,13]))

353

 here

In [326]:
targetNew

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
362,4,0,770,104.098151,30.707717,50,-26,-19,-144,661,880,104.099515,104.099248,30.707318,30.707147
363,6,1,995,104.094434,30.699710,50,-614,-1083,-120,2901,1071,104.097646,104.091222,30.704581,30.694839
364,7,2,1156,104.082974,30.693535,50,-1266,257,169,1101,1212,104.089592,104.076355,30.692372,30.694681
365,5,3,1277,104.067196,30.694802,50,-1195,16,179,1233,1322,104.073443,104.060949,30.694730,30.694874

In [339]:
#2020/06/12
import math

def getTestResult4OneTarget(targetTrajNo,
                            trajTest,
                            trajTestOri,
                            mappingTest,
                            trajTrain,
                            trajTrainOri,
                            mappingTrain,
                            epLng,epLat):
	targetTraj = trajTest.loc[trajTest[5] == targetTrajNo,].copy()
	targetTrajOri = trajTestOri.loc[trajTestOri[5] == targetTrajNo,].copy()
	targetMapping = mappingTest.loc[mappingTest[2] == targetTrajNo,].copy()
	targetNew, targetOriNew = ignoreBeginOrLastOnePointCube(targetTraj, targetTrajOri, targetMapping)
	targetNew2 = targetNew.copy()
	realTime = targetNew.iloc[-1, 10] - targetNew.iloc[0, 9]
	realTime2 = realTime
	totalTime = 0
	n = targetNew.shape[0]
	commonTime = 0
	
	ratioOfMostGap = 0.9
	timeDiff = targetTrajOri[2].iloc[1:].to_numpy() - targetTrajOri[2].iloc[:-1].to_numpy()
	timeDiff = timeDiff.astype('int')
	timeDiff = numpy.sort(timeDiff)
	iarr = math.ceil(timeDiff.size * ratioOfMostGap)
	timeDiffTop = timeDiff[iarr] * 2
    
	tempExpResult = numpy.zeros((n, 3), dtype='int')
	tempExpResult[:, 0] = targetNew.iloc[:, 10] - targetNew.iloc[:, 9]
	listArea = []
	for i2 in range(n):
		#print(i2)
		if i2 > 0:
			targetNew.iloc[i2, 9] = targetNew.iloc[i2 - 1, 9] + commonTime
		area = getOverlayOneCubeWithPointAmount(targetNew.iloc[i2,],
					trajTrain,
					3600,
					epLng,
					epLat,
					10, 0.7)
		if area is None:
			print('ERROR: index=', i2, ' area is None')
			continue
		commonTime = getTimeByMinDtw(targetNew.iloc[i2, 1],
						area,
						targetOriNew,
						targetMapping,
						trajTrain,
						trajTrainOri,
						mappingTrain)
		tempExpResult[i2, 1] = commonTime
		if i2 < (n - 1):
			cubeTimeDiff = targetNew2.iloc[i2 + 1, 9] - targetNew2.iloc[i2, 10]
			if cubeTimeDiff > timeDiffTop:
				realTime2 -= cubeTimeDiff
			else:
				commonTime = getFullTime(commonTime, targetNew.iloc[i2,], targetNew.iloc[i2 + 1,])

		tempExpResult[i2, 2] = commonTime
		totalTime += commonTime
	return (totalTime,realTime,realTime2,tempExpResult)

# here 0623

In [ ]:
#2020/06/23
import math

def getTestResult4OneTarget2(targetTrajNo,
                            trajTest,
                            trajTestOri,
                            mappingTest,
                            trajTrain,
                            trajTrainOri,
                            mappingTrain,
                            epLng,epLat):
	targetTraj = trajTest.loc[trajTest[5] == targetTrajNo,].copy()
	targetTrajOri = trajTestOri.loc[trajTestOri[5] == targetTrajNo,].copy()
	targetMapping = mappingTest.loc[mappingTest[2] == targetTrajNo,].copy()
	targetNew, targetOriNew = ignoreBeginOrLastOnePointCube(targetTraj, targetTrajOri, targetMapping)
	targetNew2 = targetNew.copy()
	realTime = targetNew.iloc[-1, 10] - targetNew.iloc[0, 9]
	realTime2 = realTime
	totalTime = 0
	n = targetNew.shape[0]
	commonTime = 0
	
	ratioOfMostGap = 0.9
	timeDiff = targetTrajOri[2].iloc[1:].to_numpy() - targetTrajOri[2].iloc[:-1].to_numpy()
	timeDiff = timeDiff.astype('int')
	timeDiff = numpy.sort(timeDiff)
	iarr = math.ceil(timeDiff.size * ratioOfMostGap)
	timeDiffTop = timeDiff[iarr] * 2
    
	tempExpResult = numpy.zeros((n, 3), dtype='int')
	tempExpResult[:, 0] = targetNew.iloc[:, 10] - targetNew.iloc[:, 9]
	listArea = []
	for i2 in range(n):
		#print(i2)
		if i2 > 0:
			targetNew.iloc[i2, 9] = targetNew.iloc[i2 - 1, 9] + commonTime
		area = getOverlayOneCubeWithPointAmount(targetNew.iloc[i2,],
					trajTrain,
					3600,
					epLng,
					epLat,
					10, 0.7)
		if area is None:
			print('ERROR: index=', i2, ' area is None')
			continue
		commonTime = getTimeByMinDtw(targetNew.iloc[i2, 1],
						area,
						targetOriNew,
						targetMapping,
						trajTrain,
						trajTrainOri,
						mappingTrain)
		tempExpResult[i2, 1] = commonTime
		if i2 < (n - 1):
			cubeTimeDiff = targetNew2.iloc[i2 + 1, 9] - targetNew2.iloc[i2, 10]
			if cubeTimeDiff > timeDiffTop:
				realTime2 -= cubeTimeDiff
			else:
				commonTime = getFullTime(commonTime, targetNew.iloc[i2,], targetNew.iloc[i2 + 1,])

		tempExpResult[i2, 2] = commonTime
		totalTime += commonTime
	return (totalTime,realTime,realTime2,tempExpResult)

In [ ]:

targetTrajNo = 4
totalTime,realTime,realTime2,tempExpResult = \
    getTestResult4OneTarget2(targetTrajNo,
                            trajTest,
                            trajTestOri,
                            mappingTest,
                            trajTrain,
                            trajTrainOri,
                            mappingTrain,
                            epLng,epLat)

In [340]:
tempExpResult

array([[110, 103, 124],
       [ 99, 170, 210],
       [161, 200, 219],
       [252, 232, 267],
       [252, 221, 282],
       [220, 210, 235],
       [149, 206, 246],
       [170, 121, 121]])

In [301]:
print(totalTime)
print(realTime)
print(realTime2)

1704
1583
1583

In [246]:
import math
ratioOfMostGap = 0.95
timeDiff = targetTrajOri[2].iloc[1:].to_numpy() - targetTrajOri[2].iloc[:-1].to_numpy()
timeDiff = timeDiff.astype('int')
timeDiff = numpy.sort(timeDiff)
print(timeDiff)
iarr = math.ceil(timeDiff.size * ratioOfMostGap)
print('iarr=',iarr,',timeDiff[]=',timeDiff[iarr])
#iarr = numpy.where((hist[0].cumsum() / hist[0].sum())>ratioOfMostGap)[0][0]
#mostTimeGap = hist[1][iarr]

[  8  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10
  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10
  11  11  11  11  11  12  16  18  18  20  20  20  20  20  21  21  21  22
  28  29  29  30  30  30  30  30  30  31  31  40  41  41  51  58  71  91
  91  99 182 242 643]
iarr= 74 ,timeDiff[]= 182

In [101]:
expResult2 = numpy.zeros((trajNoList.size+1,4),dtype='int')
expResult2[:,:3] = expResult

In [104]:
expResult = expResult2

In [ ]:
expResult[expResult[:,2]==0,:]

In [ ]:
numpy.where

In [320]:
expResult[50,]

array([ 661, 2692,    0,  661,   50])

In [318]:
deviation = numpy.absolute(expResult[1:101,0] - expResult[1:101,1])
eachAPE = deviation * 100 / expResult[1:101,0] 
eachAPE = eachAPE.astype(int)
#eachAPE[[49,6,11,60]] = 0
eachAPE

array([ 17,   0,  10,   7,  10,   5,  87,   5,   3,   9,   7,  83,  22,
        35,   9,   3,   0,   0,   1,  18,   5,   4,   8,   3,   2,   3,
        10,  36,  32,  33,  28,  18,   0,  12,   5,  10,  20,  18,  12,
         6,   5,  12,  25,  36,  33,  22,   6,  26,  13, 307,  37,  13,
        20,  23,   0,  15,  43,   9,  37,   3,  87,  13,   9,  17,  15,
        18,   1,  14,  10,  11,  26,  22,   3,   1,  16,  25,  26,  15,
         4,   0,  33,  29,  13,   1,   7,  15,   6,   4,   8,  11,   1,
        21,  17,   0,   3,  12,   9,  10,  21,   5])

In [317]:
eachAPE.mean()

12.76

In [319]:
eachAPE[49]

307

In [78]:
expResult[1:101,0]

array([ 816, 2494, 1095, 1583, 1994, 2034,  493, 1033, 1091,  722, 1972,
        779, 2270, 2152, 1546, 2363, 1389, 1590, 1316, 1942, 1802, 1425,
       1860, 1368, 1218, 1263, 3193, 3203, 1730, 1118, 2157, 1959, 1283,
       1510, 1670,  635,  922, 1056, 1449, 1501,  673, 1430, 1072, 1973,
       1463, 1562,  531, 3137, 1147,  661, 1334, 1143, 2247, 1545, 1072,
       1416, 2439,  489, 1216, 2569,  964, 3271,  907, 2172, 1115,  935,
        834, 1668,  986,  906,  888, 1336,  967, 1573, 1557, 1730, 1540,
       2709, 1056,  865, 3087, 1561,  882, 1609, 1251,  959,  789,  922,
       1257, 2670, 1819, 1975,  722, 1013,  983, 1488, 1831, 1160,  628,
       1399])

In [207]:
from dtw import dtw

targetCubeNo = targetNew.iloc[9,1]

targetTrajOriResetIndex = targetTrajOri.reset_index()
x = targetTrajOriResetIndex.loc[ 
        targetMapping.loc[ targetMapping[4] == targetCubeNo ,3] ,
        [3,4]
    ].to_numpy()

result = []
dfTrajNoWiCubeNo = trajTrain.loc[listArea[9][2],[5,1]]
n = dfTrajNoWiCubeNo.shape[0]
for i in range(n):
    tempTrajOriNo = mappingTrain.loc[ 
        (mappingTrain[2] == dfTrajNoWiCubeNo[5].iloc[i]) & 
        (mappingTrain[4] == dfTrajNoWiCubeNo[1].iloc[i])
        ,3].to_list()
    y = trajTrainOri.loc[ 
        (trajTrainOri[5] == dfTrajNoWiCubeNo[5].iloc[i]) & 
        (trajTrainOri[1].isin( tempTrajOriNo ))
        ,[3,4]].to_numpy()
    d, cost_matrix, acc_cost_matrix, path = dtw(x,y,getDistance)
    result.append(d)

In [209]:
result

[7243.0,
 6552.0,
 6447.0,
 7300.0,
 5601.0,
 6198.0,
 10675.0,
 2512.0,
 8184.0,
 6730.0,
 2340.0,
 2563.0,
 4279.0,
 4279.0,
 7274.0,
 8718.0,
 9851.0,
 6906.0,
 6906.0,
 6491.0,
 7368.0,
 7553.0,
 7553.0,
 9621.0,
 8958.0,
 8958.0,
 8958.0,
 7369.0,
 3034.0,
 6679.0,
 6423.0,
 6245.0,
 6812.0,
 11585.0,
 10008.0,
 8777.0,
 7473.0,
 3392.0,
 2903.0,
 2932.0,
 8374.0,
 10086.0,
 4609.0,
 4505.0,
 4986.0,
 10473.0,
 9531.0,
 8067.0,
 6360.0,
 7979.0,
 9746.0,
 7438.0,
 10177.0,
 6925.0,
 7611.0,
 8495.0,
 4271.0,
 3228.0,
 6724.0,
 6951.0,
 5611.0,
 4886.0,
 9415.0,
 6912.0,
 8778.0,
 3902.0,
 7425.0,
 7992.0,
 8630.0,
 8464.0,
 2482.0,
 2482.0,
 6954.0,
 4785.0,
 3039.0,
 4002.0,
 4002.0,
 9462.0,
 7632.0,
 6158.0,
 9516.0,
 7304.0,
 8531.0,
 9075.0,
 7515.0,
 8764.0,
 7885.0,
 8930.0,
 2863.0,
 9705.0,
 7292.0,
 4188.0,
 1167.0,
 11645.0,
 7790.0,
 8951.0,
 7089.0,
 8185.0,
 6083.0,
 6704.0,
 3125.0,
 8038.0,
 6957.0,
 7269.0,
 7287.0,
 7650.0,
 9823.0,
 8928.0,
 8232.0,
 9770.0,
 7660.0,
 7871.0,
 8387.0,
 7228.0,
 7279.0,
 9756.0,
 8378.0,
 7749.0,
 9706.0,
 9904.0,
 8444.0,
 8500.0]

In [194]:
y

array([[104.117255,  30.605778],
       [104.113978,  30.605508],
       [104.111175,  30.605103],
       [104.109521,  30.604863],
       [104.107584,  30.604774],
       [104.105169,  30.604757],
       [104.103021,  30.605001]])

In [148]:
targetNew.iloc[9,]

0        6.000000
1        9.000000
2     4834.000000
3      104.098311
4       30.606151
5       60.000000
6     -916.000000
7      -81.000000
8     -175.000000
9     3543.000000
10    4958.000000
11     104.103096
12     104.093527
13      30.606759
14      30.606032
Name: 437, dtype: float64

In [155]:
targetTrajOriResetIndex = targetTrajOri.reset_index()
x = targetTrajOriResetIndex.loc[ targetMapping.loc[ targetMapping[4] == 9 ,3] ,[3,4]].to_numpy()

array([[104.103096,  30.606759],
       [104.102116,  30.605729],
       [104.099489,  30.605544],
       [104.096312,  30.605829],
       [104.094837,  30.606046],
       [104.093527,  30.606032]])

In [205]:
dfTrajNoWiCubeNo = trajTrain.loc[listArea[9][2],[5,1]]
#dfTrajNoWiCubeNo.iloc[0,]

tempTrajOriNo = mappingTrain.loc[ 
    (mappingTrain[2] == dfTrajNoWiCubeNo[5].iloc[0]) & 
    (mappingTrain[4] == dfTrajNoWiCubeNo[1].iloc[0])
    ,3].to_list()

y = trajTrainOri.loc[ (trajTrainOri[5] == dfTrajNoWiCubeNo[5].iloc[0]) & (trajTrainOri[1].isin( tempTrajOriNo )),[3,4]]
y.index[0]

14608

In [333]:
import pandas as pd
index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
df = pd.DataFrame({'http_status': [200, 200, 404, 404, 301],
                  'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
                  index=index)
#df
new_index = ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10',
             'Chrome']
df.set_index(new_index)

KeyError: "None of ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10', 'Chrome'] are in the columns"